version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ '/usr/src/app/entrypoint.sh' ]
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_ENV=${FLASK_ENV}
      - APP_SETTINGS=${APP_SETTINGS}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - SHARED_SECRET_KEY=${SHARED_SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

    depends_on:
      - api-dev-db
      - api-test-db

  api-dev-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  api-test-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

